export const GET_PRODUCTS = "GET_PRODUCTS";
export const CHOSE_A_CATEGORY = "CHOSE_A_CATEGORY";
export const CHOSE_A_SORTBY = "CHOSE_A_SORTBY";
export const ADD_MORE_PRODUCT = "ADD_MORE_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"